{{ config(materialized='table') }}

SELECT DISTINCT
    O_ORDERDATE as DATE,
    SUM(O_TOTALPRICE) OVER(PARTITION BY O_ORDERDATE ) as cumulative
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS" 
ORDER BY DATE ASC