
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          # - accepted_values:
          #     values: [1,2]  ##list of the values that we want
          #     quote: false    ## ensure de numbers in the list and not striings

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

        
